-- CreateEnum
CREATE TYPE "SegmentKey" AS ENUM ('A_CONSTRUCAO_SERVICOS_LAR', 'B_RESTAURACAO_CAFES_PASTELARIAS', 'C_CABELEIREIROS_BARBEARIAS_ESTETICA', 'D_OFICINAS_AUTO_PNEUS_SERVICOS_AUTO', 'E_MERCEARIAS_MERCADOS_PADARIAS', 'F_LOJAS_ROUPA_CALCADO_DECORACAO', 'G_CLINICAS_SAUDE_WELLNESS', 'H_ALOJAMENTO_LOCAL_HOTEIS', 'I_ESCOLAS_CURSOS_CENTROS_ESTUDO', 'J_PROFISSIONAIS_LIBERAIS_SERVICOS');

-- DropIndex
DROP INDEX "Contact_reviveAt_idx";

-- DropIndex
DROP INDEX "Contact_state_idx";

-- AlterTable
ALTER TABLE "Contact" ADD COLUMN     "segmentKey" "SegmentKey";
